version: '3'

volumes:
  db-data-mariadb:
    driver: local

  db-data-mariadb-config:
    driver: local

services:
  linda-mariadb:
    image: mariadb:10.8.2-rc-focal
    container_name: linda-mariadb
    environment:
      MARIADB_DATABASE: "linda-data"
      MARIADB_USER: "linda-data"
      MARIADB_PASSWORD: "linda-data"
      MARIADB_ROOT_PASSWORD: "root"
    restart: always
    networks:
      - linda-net
    expose:
      - 3306
    volumes:
      - db-data-mariadb:/var/lib/mysql
      - db-data-mariadb-config:/etc/mysql

  linda:
    image: linda:0.3.0.beta.0
    container_name: linda
    networks:
      - linda-net
    ports:
      - "8080:8080"
    depends_on:
      - linda-mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://linda-mariadb:3306/linda-data

networks:
  linda-net:
    driver: bridge
