version: '3'

volumes:
  db-data-postgres:
    driver: local

  db-data-postgres-config:
    driver: local

services:
  linda-postgres:
    image: postgres:15beta2-bullseye
    container_name: linda-postgres
    environment:
      POSTGRES_DB: "linda_data"
      POSTGRES_USER: "linda_data"
      POSTGRES_PASSWORD: "linda_data"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    expose:
      - 5432
    networks:
      - linda-net
    volumes:
      - db-data-postgres:/var/lib/postgresql/data
      - db-data-postgres-config:/var/lib/postgresql/dataConfig

  linda:
    image: linda:0.8.0-beta.0
    container_name: linda
    networks:
      - linda-net
    ports:
      - "9292:9292"
    depends_on:
      - linda-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://linda-postgres:5432/linda_data
    restart: on-failure

networks:
  linda-net:
    driver: bridge
