version: '3'

volumes:
  db-data-postgres:
    driver: local

  db-data-postgres-config:
    driver: local

services:
  linda-postgres:
    image: postgres:15beta2-bullseye
    container_name: linda-postgres
    environment:
      POSTGRES_DB: "linda_data"
      POSTGRES_USER: "linda_data"
      POSTGRES_PASSWORD: "linda_data"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data-postgres:/var/lib/postgresql/data
      - db-data-postgres-config:/var/lib/postgresql/dataConfig