spring:
  application:
    name: "linda"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:5432/linda-data
    username: linda-data
    password: linda-data

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none # required for liquibase migrations

  liquibase:
    change-log: db/changelog/db.changelog-main.xml

  main:
    allow-circular-references: true

  config:
    activate:
      on-profile: production

springdoc:
  api-docs:
    path: /specs

  swagger-ui:
    path: /docs