spring:
  profiles:
    active: "production"

  application:
    name: "linda"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/linda_data
    username: linda_data
    password: linda_data

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none # required for liquibase migrations

  liquibase:
    change-log: db/changelog/db.changelog-main.xml

  main:
    allow-circular-references: true
    banner-mode: off

server:
  port: 9292