spring:
  # Using deprecated property,
  # see: https://stackoverflow.com/questions/71902150/spring-config-activate-on-profile-somehow-causes-database-connection-issues
  profiles:
    active: "production"

  application:
    name: "linda"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:5432/linda-data
    username: linda-data
    password: linda-data

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none # required for liquibase migrations

  liquibase:
    change-log: db/changelog/db.changelog-main.xml

  main:
    allow-circular-references: true

springdoc:
  api-docs:
    path: /specs

  swagger-ui:
    path: /docs