management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: debug

spring:
  jpa:
    show-sql: true

simple-security:
  authentication-secret: secret
  enabled: false

linda:
  base-interface:
    automatic-utm-creation: true